spring.application.name=auth-service
server.port=8081

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/shoppe_auth?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Password123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1

# JWT
shoppe.jwt.secret=9B916BBAAECFDE6A5822FBEB667F5B6F5A29B12E7B357CCD4D1898748DA8C88B0
shoppe.jwt.expirationMs=86400000

server.error.include-message=always
