spring.application.name=shoppe-backend

# Database Configuration (H2 in memory instead of MySQL)
spring.datasource.url=jdbc:h2:mem:shoppe_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
shoppe.jwt.secret=9B916BBAAECFDE6A5822FBEB667F5B6F5A29B12E7B357CCD4D1898748DA8C88B0
shoppe.jwt.expirationMs=86400000

# Server Configurations
server.port=8080
server.error.include-message=always
